### ISSUE TITLE
Architect Login Issue

### ISSUE THREAD

**Issue by anyplaceucy** [dmsl/anyplace#66]
Google changed its API so the Anyplace login feature was affected. A solution has been provided and Architect 2.8 is already testable through the DEV site. A release on our PUBLIC service is expected by tomorrow.

The Anyplace Team

**Comment by pss921** [comment]
Still i'm getting this error call 'Something went wrong while fetching buildings' when login to the anyplace Architect. Please solve my issue.

**Comment by dvaler01** [comment]
Hello there.

We had a problem with couchbase yesterday but now it's ok.

Dimitrios Valeris.

**Comment by pss921** [comment]
Thank you Dimitrios. I’m using Anyplace Architect in Public IP using localhost:9000. I’m still getting the error that I have mansion on previous comment. When i'm using Dev site it works fine.

**Comment by anyplaceucy** [comment]
Fixed in 2.8

**Comment by ZeeshanMohammad** [comment]
where can we find the files of anyplace 2.8

**Comment by anyplaceucy** [comment]
They are currently under the DEVELOP branch but will be merged soon https://github.com/dmsl/anyplace/tree/develop

The Anyplace Team

**Comment by ZeeshanMohammad** [comment]
I am trying with the develop tag architect module.But still stuck with the same issue of unable to place buildings.i have followed the read me document and implemented in the same way it is. But still the same issue as anyplace master.Can u guys please help me with that.
![projmid](https://cloud.githubusercontent.com/assets/18724084/19614144/792ddbb4-97b7-11e6-93d2-f92606d1f6c1.PNG)
